apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app
spec:
  selector:
    matchLabels:
      app: cicd-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
        - name: cicd-app
          image: confidencedev/cicd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082 #The port the container is running in the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: cicd-svc
spec:
  selector:
    app: cicd-app
  ports:
    - port: 80 #The port the service id running in the cluster
      targetPort: 8082 #The port exposed by the service
  type: NodePort #Type of the service